[General]

Background="/usr/share/sddm/wallpapers/CnepzHx.jpeg"
font="Cantarell"
Padding="50"
CornerRadius="5"
GeneralFontSize="9"
LoginScale="0.175"

UserPictureBorderWidth="5"
UserPictureBorderColor="#667BBE"
UserPictureColor="#667BBE"

TextFieldColor="#667BBE"
TextFieldTextColor="#E6EBFF"

LoginButtonTextColor="#E6EBFF"
LoginButtonBgColor="#667BBE"
LoginButtonText="☆ Login ☆"

PopupBgColor="#E6EBFF"
PopupHighlightColor="#667BBE"

SessionButtonColor="#667BBE"
SessionIconColor="#E6EBFF"

PowerButtonColor="#667BBE"
PowerIconColor="#E6EBFF"

DateColor="#667BBE"
DateSize="30"
DateIsBold="false"
DateOpacity="0.8"
DateFormat="dddd, MMMM d"

TimeColor="#667BBE"
TimeSize="60"
TimeIsBold="true"
TimeOpacity="0.8"
TimeFormat="hh:mm AP"
