enable_audio_bell no

font_size 17.0
background_opacity   0.85

foreground #E6EBFF

color0  #667BBE
color1  #667BBE
color2  #667BBE
color3  #667BBE
color4  #667BBE
color5  #667BBE
color6  #667BBE
color7  #E6EBFF
color8  #667BBE
color9  #667BBE
color10 #667BBE
color11 #667BBE
color12 #667BBE
color13 #667BBE
color14 #667BBE
color15 #E6EBFF


# BEGIN_KITTY_THEME
# Base4Tone_Classic_S Dark
# include current-theme.conf
# END_KITTY_THEME
