input {
    kb_layout = de
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 bedeutet keine Änderung
}
cursor {
    no_hardware_cursors = true
}

general {
    col.active_border = rgba(667bbeee)

}
exec-once = swww-daemon
exec-once = swww img /home/existential_crisis/Bilder/CnepzHx.jpeg
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = qs
$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit
bind = $mainMod, D, exec, wofi --show drun --style ~/.config/wofi/style.css
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, 1, workspace, 1 
bind = $mainMod, 2, workspace, 2 
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy

# --- MONITOR SETUP ---
# ASUS 27" (Links, 180Hz)
monitor=DP-2, 2560x1440@180, 0x0, 1

# Alienware 34" (Mitte, 165Hz)
monitor=DP-1, 3440x1440@165, 2560x0, 1

# Dell 24" (Rechts, Hochkant, 60Hz)
# Transform 1 dreht 90 Grad. Falls es falsch rum ist, nimm 3.
monitor=HDMI-A-1, 1920x1200@60, 6000x0, 1, transform, 3

bind = $mainMod, left, movewindow, l
bind = $mainMod, right, movewindow, r
bind = $mainMod, up, movewindow, u
bind = $mainMod, down, movewindow, d
bind = SUPER, X, exec, ~/powermenu.sh
bindm = $mainMod, mouse:272, movewindow
bind = $mainMod SHIFT, left, movewindow, mon:l
bind = $mainMod SHIFT, right, movewindow, mon:r
# --- THE GLASSY THEME ---
decoration {
    rounding = 13
    blur {
        enabled = true
        size = 10    # Increased for better "glass" feel
        passes = 3   # More passes = smoother blur
    }
}

# Apply blur to our tools
layerrule = blur = wofi

windowrule = match:class steam_app_3513350, fullscreen on
